name: CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test PPanGGOLiN on ${{ matrix.os }} with python ${{ matrix.python-version }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest'] # 'ubuntu-latest'] # ,] 
        python-version: ['3.10'] # , '3.9', ]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Setting up miniconda
    - uses: conda-incubator/setup-miniconda@v2
      with:
        condarc-file: .condarc.yml
        activate-environment: test
        python-version: ${{ matrix.python-version }}
    # Install the dependencies
    - name: Set up test environment
      shell: bash -l {0}
      run: |
        conda install -y -q --file requirements.txt 
        conda install -y -q pytest
        conda list
        pip install wheel
        pip install .
        
    # Check that it is installed and displays help without error
    - name: Check that PPanGGOLiN is installed
      shell: bash -l {0}
      run: |
        ppanggolin --version
        ppanggolin --help
        
    # Check that unit tests are all passing
    - name: Unit tests
      shell: bash -l {0}
      run: pytest
    
